In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
dataset["classification_yes"].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [9]:
dep=dataset["classification_yes"]

In [10]:
indep.shape

(399, 27)

In [11]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: uint8

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
from sklearn.model_selection import GridSearchCV

param_grid = {'n_neighbors': [3, 5, 7, 9],'weights': ['uniform', 'distance'],'p': [1, 2] }

In [19]:

grid = GridSearchCV(KNeighborsClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.

Fitting 3 folds for each of 16 candidates, totalling 48 fits

[Parallel(n_jobs=-1)]: Done  28 tasks      | elapsed:   13.2s
[Parallel(n_jobs=-1)]: Done  48 out of  48 | elapsed:   17.2s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=-1,
             param_grid={'n_neighbors': [3, 5, 7, 9], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [20]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test_) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

In [21]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [22]:
print(grid.best_params_)

{'n_neighbors': 9, 'p': 1, 'weights': 'distance'}

In [23]:
table=pd.DataFrame.from_dict(re)

In [24]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006336,3.300885e-03,0.013000,1.414392e-03,3,1,uniform,"{'n_neighbors': 3, 'p': 1, 'weights': 'uniform'}",0.723869,0.778478,0.730769,0.744423,0.024312,6
1,0.004004,1.461091e-06,0.007281,1.179138e-03,3,1,distance,"{'n_neighbors': 3, 'p': 1, 'weights': 'distance'}",0.712809,0.800058,0.730769,0.747943,0.037674,3
2,0.004002,1.520405e-06,0.010333,4.715394e-04,3,2,uniform,"{'n_neighbors': 3, 'p': 2, 'weights': 'uniform'}",0.679688,0.778892,0.729919,0.729498,0.040577,10
3,0.004335,4.725510e-04,0.004332,4.701340e-04,3,2,distance,"{'n_neighbors': 3, 'p': 2, 'weights': 'distance'}",0.679573,0.800630,0.741616,0.740603,0.049519,8
4,0.005335,1.886662e-03,0.010333,4.719885e-04,5,1,uniform,"{'n_neighbors': 5, 'p': 1, 'weights': 'uniform'}",0.723391,0.745520,0.752426,0.740401,0.012386,9
5,0.004669,9.439773e-04,0.005666,1.699862e-03,5,1,distance,"{'n_neighbors': 5, 'p': 1, 'weights': 'distance'}",0.723391,0.778478,0.740654,0.747534,0.023045,5
6,0.003999,4.824991e-06,0.013999,2.160679e-03,5,2,uniform,"{'n_neighbors': 5, 'p': 2, 'weights': 'uniform'}",0.690449,0.734671,0.704545,0.709909,0.018476,15
7,0.004336,4.725506e-04,0.005063,1.502732e-03,5,2,distance,"{'n_neighbors': 5, 'p': 2, 'weights': 'distance'}",0.679573,0.778478,0.716726,0.724957,0.040865,12
8,0.004716,5.056043e-04,0.013909,1.636028e-03,7,1,uniform,"{'n_neighbors': 7, 'p': 1, 'weights': 'uniform'}",0.767649,0.723683,0.752426,0.747902,0.018262,4
9,0.005226,1.380243e-03,0.004999,5.619580e-07,7,1,distance,"{'n_neighbors': 7, 'p': 1, 'weights': 'distance'}",0.744916,0.778892,0.752426,0.758769,0.014595,2
10,0.006728,3.853683e-03,0.011080,8.341913e-04,7,2,uniform,"{'n_neighbors': 7, 'p': 2, 'weights': 'uniform'}",0.701577,0.712420,0.695551,0.703211,0.006977,16
11,0.005290,1.262639e-03,0.003995,4.785560e-06,7,2,distance,"{'n_neighbors': 7, 'p': 2, 'weights': 'distance'}",0.668626,0.756992,0.718102,0.714560,0.036229,13
12,0.004003,7.867412e-07,0.010999,1.415966e-03,9,1,uniform,"{'n_neighbors': 9, 'p': 1, 'weights': 'uniform'}",0.756782,0.756954,0.718102,0.744043,0.018240,7
13,0.006337,2.055288e-03,0.004332,4.719902e-04,9,1,distance,"{'n_neighbors': 9, 'p': 1, 'weights': 'distance'}",0.767649,0.779084,0.741616,0.762863,0.015654,1
14,0.004335,4.725506e-04,0.011333,2.055520e-03,9,2,uniform,"{'n_neighbors': 9, 'p': 2, 'weights': 'uniform'}",0.756954,0.689598,0.692204,0.712997,0.031189,14
15,0.006667,3.771975e-03,0.009334,4.785548e-03,9,2,distance,"{'n_neighbors': 9, 'p': 2, 'weights': 'distance'}",0.745869,0.712420,0.718102,0.725491,0.014634,11

In [25]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'n_neighbors': 9, 'p': 1, 'weights': 'distance'}: 0.47029200909249863

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [26]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[ 0 51]
 [ 0 82]]

In [27]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        51
           1       0.62      1.00      0.76        82

    accuracy                           0.62       133
   macro avg       0.31      0.50      0.38       133
weighted avg       0.38      0.62      0.47       133

In [28]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.8433763749402198

In [29]:
table_pr=pd.DataFrame()

In [30]:
print(X_test)

           age     bp   al   su         bgr    bu   sc         sod       pot  \
132  46.000000   70.0  0.0  0.0  100.000000  47.0  0.5  142.000000  3.500000
309  66.000000   90.0  2.0  0.0  153.000000  76.0  3.3  137.528754  4.627244
334  69.000000   70.0  0.0  0.0   83.000000  42.0  1.2  139.000000  3.700000
196  55.000000  100.0  1.0  4.0  297.000000  53.0  2.8  139.000000  4.500000
246  60.000000   90.0  2.0  0.0  105.000000  53.0  2.3  136.000000  5.200000
..         ...    ...  ...  ...         ...   ...  ...         ...       ...
349  71.000000   70.0  0.0  0.0   81.000000  18.0  0.8  145.000000  5.000000
168  50.000000   80.0  0.0  0.0  137.000000  46.0  0.8  139.000000  5.000000
150  48.000000  100.0  0.0  0.0  103.000000  79.0  5.3  135.000000  6.300000
392  51.492308   60.0  3.0  0.0  148.112676  34.0  1.2  137.528754  4.627244
66   34.000000   60.0  0.0  0.0   91.000000  49.0  1.2  135.000000  4.500000

          hrmo  ...  rbc_normal  pc_normal  pcc_present  ba_present  htn_yes  \
132  16.400000  ...           1          1            0           0        0
309  12.518156  ...           1          1            0           1        0
334  16.200000  ...           1          1            0           0        0
196  11.200000  ...           1          1            0           0        1
246  11.100000  ...           0          1            0           0        0
..         ...  ...         ...        ...          ...         ...      ...
349  14.700000  ...           1          1            0           0        0
168  14.100000  ...           1          1            0           0        0
150   6.300000  ...           1          1            0           0        1
392  10.800000  ...           0          0            0           0        0
66   13.500000  ...           1          1            0           0        0

     dm_yes  cad_yes  appet_yes  pe_yes  ane_yes
132       0        0          1       0        0
309       0        0          0       0        0
334       0        0          1       0        0
196       1        0          1       0        0
246       0        0          1       0        0
..      ...      ...        ...     ...      ...
349       0        0          1       0        0
168       0        0          1       0        0
150       0        1          0       0        0
392       0        0          1       0        0
66        0        0          1       0        0

[133 rows x 27 columns]